Fix a bug in test filtering.

diff --git a/src/main/scripts/bin/testrunner b/src/main/scripts/bin/testrunner
--- a/src/main/scripts/bin/testrunner
+++ b/src/main/scripts/bin/testrunner
@@ -33,9 +33,11 @@ TESTRUNNER_SPECIFICATION='{
 }'
 
 function list_executable_tests() {
-  local _workdir="${1%/}"
+  local _workdir="${1%/}" _filter="${2}"
+  # shellcheck disable=SC2016
   find "${_workdir}" -name '*.json' -or -name '*.sh' |
     grep -E '(test-.+|.*-test|test)(\.sh|\.json)' |
+    filter_file '[[ "${_each}" =~ '"${_filter}"' ]]' |
     sed -r 's!'"${_workdir}/"'!!' |
     sort
 }
@@ -223,7 +225,7 @@ function run_tests() {
   _test_rootdir="${_test_rootdir%/}"
   local -a _tests
   info_begin "_test_rootdir: '${_test_rootdir}'; _test_filter: '${_test_filter}'; _test_reportdir: '${_test_reportdir}'"
-  mapfile -t _tests < <(list_executable_tests "${_test_rootdir}" | grep -E "${_test_filter}" || abort "Failed to list tests in directory:'${_test_rootdir}' with filter: '${_test_filter}'")
+  mapfile -t _tests < <(list_executable_tests "${_test_rootdir}" "${_test_filter}" || abort "Failed to list tests in directory:'${_test_rootdir}' with filter: '${_test_filter}'")
   [[ "${#_tests[@]}" -gt 0 ]] || abort "No available tests.: (directory: '${_test_rootdir}', filter: '${_test_filter}')"
   local _passed=0 _skipped=0 _failed=0 _error=0 _run=0 _numtests=0 _test_results=()
   local _i
