WIP: Docker support

diff --git a/src/main/scripts/bin/testrunner b/src/main/scripts/bin/testrunner
--- a/src/main/scripts/bin/testrunner
+++ b/src/main/scripts/bin/testrunner
@@ -42,7 +42,7 @@ function prepare_tests() {
   if [[ "${_srcdir}" != "${_outdir}" ]]; then
     # Create a directory for output.
     mkdir -p "${_outdir}"
-    cp -r "${_srcdir}"/* "${_outdir}"/
+    cp -r "${_srcdir}"/* "${_outdir}"/ || abort "Failed to copy from '${_srcdir}' to '${_outdir}'"
   fi
   # Compile tests
   __compile_tests "${_outdir}" "${_is_parallel}"
