Implement 'testrunner' (WIP)

diff --git a/src/bin/testrunner b/src/bin/testrunner
--- a/src/bin/testrunner
+++ b/src/bin/testrunner
@@ -17,8 +17,8 @@ function precheck_each_test() {
 }
 
 function execute_each_test() {
-  local _testname="${1}" _testdir="${2}" _out="${3}"
-  __execute_test_stage "${_testname}" "${_testdir}" "execute" "success" "execution" "${_out}"
+  local _testname="${1}" _testdir="${2}" _errout="${3}"
+  __execute_test_stage "${_testname}" "${_testdir}" "execute" "success" "execution" "${_errout}"
 }
 
 function __execute_test_stage() {
@@ -27,22 +27,38 @@ function __execute_test_stage() {
   local _stage_name="${3}" # execute / precheck
   local _attr_name="${4}"  # .successful / .precheck
   local _label="${5}"      # execution / precheck
-  local _out="${6}"
+  local _errout="${6}"
   local _result_json _ret
-  _result_json="$("${_stage_name}_test" "${_testname}" "${_testdir}")"
-  if __is_valid "${_result_json}"; then
+  info_begin "__execute_test_stage: ${_stage_name}: (${_testname})"
+  _result_json="$("${_stage_name}_test" "${_testname}" "${_testdir}" 2>"${_errout}")" || {
+    error "DRIVER ERROR DETECTED: '${_stage_name}_test' in $(test_driver_name)"
+  }
+  debug "_result_json: '${_result_json}'"
+  if (__is_valid "${_result_json}" "${_attr_name}"); then
+    debug "valid"
     echo "${_result_json}"
   else
-    jq -ncrM --arg v "${_result_json}" '{"report":{"result":{"'"${_label}"'":false},"driverOutput":$v}}'
+    debug "not valid"
+    local _err
+    _err="$(cat "${_errout}")"
+    jq -ncrM --arg v "${_result_json}" --arg w "${_err}" '{"report":{"result":{"'"${_label}"'":false},"driverOutput":{"stdout":$v,"stderr":$w}}}'
   fi
+  info_end "__execute_test_stage: ${_stage_name}: (${_testname})"
   return 0
 }
 
 function __is_valid() {
-  local _content="${1}"
-  echo "${_content}" | jq ".report.result.${_attr_name}" >& /dev/null || return 1
-  json_object_merge "${_content}" '{}' >& /dev/null || return 1
-  return 0
+  local _content="${1}" _attr_name="${2}"
+  local _exit_code=0
+  info_begin "_attr_name: '${_attr_name}'"
+  (echo "${_content}" | jq ".report.result.${_attr_name}") >&/dev/null || {
+    _exit_code=1
+  }
+  json_object_merge "${_content}" '{}' >&/dev/null || {
+    _exit_code=1
+  }
+  info_end "_attr_name: '${_attr_name}'"
+  return "${_exit_code}"
 }
 
 #   run
@@ -52,16 +68,23 @@ function __is_valid() {
 #   error
 #   tests[@]
 __run_each_test_dir="out"
+__run_each_test_test_driver_name="unknown"
 function run_each_test() {
   local _testname="${1}" _testdir="${2}"
   local _precheck_result_file _execution_result_file
   info_begin "'${1}'"
   if [[ "${_testname}" == *.sh ]]; then
     info "Test type: 'scripttest'"
-    source "${BUD_LIB}/testdrivers/scripttest.rc"
+    __run_each_test_test_driver_name="${BUD_LIB}/testdrivers/scripttest.rc"
+    # shellcheck disable=SC1090
+    source "${__run_each_test_test_driver_name}"
     __run_each_test_dir="${_testdir}/${_testname%.sh}"
     function bud__directory_for_output() {
       echo "${__run_each_test_dir}"
+    }
+
+    function test_driver_name() {
+      echo "${__run_each_test_test_driver_name}"
     }
     local _dir
     _dir="$(bud__directory_for_output)"
@@ -90,11 +113,6 @@ function run_each_test() {
     debug "trying to execute: '${_testname}'"
     _execution_result="$(execute_each_test "${_testname}" "${_testdir}" "${_execution_result_file}")"
     debug "_execution_result: '${_execution_result}'"
-    local _execution_result_json_boolean
-    _execution_result_json_boolean="$(echo "${_execution_result}" | jq -crM '.report.result.success')"
-    if [[ "${_execution_result_json_boolean}" != true ]]; then
-      _execution_result="$(jq -ncrM --arg v "${_execution_result_json_boolean}" '{"report":{"execution":false,"driverOutput":$v}}')"
-    fi
     _test_result_json="$(json_object_merge "${_execution_result}" "${_test_result_json}")"
   fi
   debug "_test_result_json: '${_test_result_json}'"
